server:
  port: 9001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root123
  main:
    banner-mode: off
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
  cache:
    type: redis
    cache-names: "country,student"
#    redis:
#      cache-null-values: true
#      key-prefix: cache_
#      use-key-prefix: true
#      enable-statistics: true
#      time-to-live: 1
  redis:
    host: localhost
    port: 6379
#    password: 13205
    timeout: 1000
    ssl: false
    lettuce:
      pool:
        max-wait: 1000
        max-active: 1000

# https://github.com/microsoftarchive/redis/releases