server:
  port: 9001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        connection:
          charset: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  sql:
    init:
      mode: never
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    timeout: 1000
#    username:
#    password: 13205

# https://github.com/microsoftarchive/redis/releases