server:
  port: 9001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        connection:
          charset: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  sql:
    init:
      mode: always
  cache:
    type: redis
    cache-names: "country"
    redis:
      cache-null-values: true
      key-prefix: cache_
      use-key-prefix: true
      enable-statistics: true
      time-to-live: 1
  redis:
    host: localhost
    port: 6379
#    password: 13205
    timeout: 1000
    ssl: false
    lettuce:
      pool:
        max-wait: 1000
        max-active: 1000

# https://github.com/microsoftarchive/redis/releases