server:
  port: 9001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root123
  main:
    banner-mode: off
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  cache:
    type: redis
    cache-names: "country,student"
    redis:
      time-to-live: 60000
      cache-null-values: true
      key-prefix: cache_
      use-key-prefix: true
      enable-statistics: true
  sql:
    init:
      mode: never
  redis:
    host: localhost
    port: 6379
#    password: 13205
    timeout: 1000
    ssl: false
    jedis:
      pool:
        max-wait: 1000
        max-active: 1000
